name: pull-request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          architecture: x64
          cache: 'maven'

      - name: Check Copyright
        run: mvn license:check

      - name: Build and Test
        run: mvn clean verify

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_ACCESS_TOKEN }}
